DECLARE @CATEGORIA_INFORMATICA INTEGER;
DECLARE @CATEGORIA_ESCRITORIO INTEGER;
DECLARE @PRODUTO_COMPUTADOR INTEGER;
DECLARE @PRODUTO_IMPRESSORA INTEGER;
DECLARE @PRODUTO_MOUSE INTEGER;
DECLARE @ESTADO_SP INTEGER;
DECLARE @ESTADO_MG INTEGER;
DECLARE @CLIENTE_ID INTEGER;
DECLARE @CIDADE_ID INTEGER;
DECLARE @PEDIDO_ID INTEGER;
DECLARE @PAGAMENTO_ID INTEGER;
DECLARE @ENDERECO_ID INTEGER;

INSERT INTO CATEGORIA (NOME) values ('Informática');
INSERT INTO CATEGORIA (NOME) values ('Escritório');

SET @CATEGORIA_INFORMATICA = SELECT ID FROM CATEGORIA WHERE NOME = 'Informática'
SET @CATEGORIA_ESCRITORIO = SELECT ID FROM CATEGORIA WHERE NOME = 'Escritório'

INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Computador', 2000.0);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Impressora', 800.0);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Mouse', 80.0);

SET @PRODUTO_COMPUTADOR = SELECT ID FROM PRODUTO WHERE NOME = 'Computador'
SET @PRODUTO_IMPRESSORA = SELECT ID FROM PRODUTO WHERE NOME = 'Impressora'
SET @PRODUTO_MOUSE = SELECT ID FROM PRODUTO WHERE NOME = 'Mouse'

INSERT INTO PRODUTO_CATEGORIA (CATEGORIA_ID, PRODUTO_ID) VALUES (@CATEGORIA_INFORMATICA, @PRODUTO_COMPUTADOR);
INSERT INTO PRODUTO_CATEGORIA (CATEGORIA_ID, PRODUTO_ID) VALUES (@CATEGORIA_ESCRITORIO, @PRODUTO_IMPRESSORA);
INSERT INTO PRODUTO_CATEGORIA (CATEGORIA_ID, PRODUTO_ID) VALUES (@CATEGORIA_ESCRITORIO, @PRODUTO_MOUSE);

INSERT INTO ESTADO (NOME) VALUES ('São Paulo');
INSERT INTO ESTADO (NOME) VALUES ('Minas Gerais');

SET @ESTADO_SP = SELECT ID FROM ESTADO WHERE NOME = 'São Paulo'
SET @ESTADO_MG = SELECT ID FROM ESTADO WHERE NOME = 'Minas Gerais'

INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('Uberlândia', @ESTADO_MG);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('Campinas', @ESTADO_SP);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('São Paulo', @ESTADO_SP);

INSERT INTO CLIENTE (NOME, CPFOUCNPJ, TIPO_CLIENTE) VALUES ('Maria Silva', '368120148', 1);

SET @CLIENTE_ID = SELECT ID FROM CLIENTE WHERE NOME = 'Maria Silva';

INSERT INTO TELEFONES(CLIENTE_ID, TELEFONES) VALUES (@CLIENTE_ID, '27563218');
INSERT INTO TELEFONES(CLIENTE_ID, TELEFONES) VALUES (@CLIENTE_ID, '14563208');

SET @CIDADE_ID = SELECT ID FROM CIDADE WHERE NOME = 'Uberlândia'

INSERT INTO ENDERECO (LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CLIENTE_ID, CIDADE_ID) VALUES ('Rua Flores', '300', 'Apt 203', 'Jardim', '38220834', @CLIENTE_ID, @CIDADE_ID);

SET @CIDADE_ID = SELECT ID FROM CIDADE WHERE NOME = 'São Paulo'

INSERT INTO ENDERECO (LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CLIENTE_ID, CIDADE_ID) VALUES ('Avenida Matos', '105', 'Sala 800', 'Centro', '38220834', @CLIENTE_ID, @CIDADE_ID);


SET @CLIENTE_ID = SELECT ID FROM CLIENTE WHERE NOME = 'Maria Silva';
SET @ENDERECO_ID = SELECT ID FROM ENDERECO WHERE LOGRADOURO = 'Rua Flores';
INSERT INTO PEDIDO (INSTANTE, CLIENTE_ID, ENDERECO_DE_ENTREGA_ID) VALUES ('2017-05-30', @CLIENTE_ID, @ENDERECO_ID);

SET @ENDERECO_ID = SELECT ID FROM ENDERECO WHERE LOGRADOURO = 'Avenida Matos';
INSERT INTO PEDIDO (INSTANTE, CLIENTE_ID, ENDERECO_DE_ENTREGA_ID) VALUES ('2017-09-15', @CLIENTE_ID, @ENDERECO_ID);

INSERT INTO PAGAMENTO (PEDIDO_ID, ESTADO_PAGAMENTO, CLIENTE_ID, ENDERECO_ID) VALUES (1, 1, 1, @ENDERECO_ID)
INSERT INTO PAGAMENTO_COM_CARTAO (NUMERO_DE_PARCELAS, PEDIDO_ID) VALUES (6, 1)

INSERT INTO PAGAMENTO (PEDIDO_ID, ESTADO_PAGAMENTO, CLIENTE_ID, ENDERECO_ID) VALUES (2, 2, 1, @ENDERECO_ID)
INSERT INTO PAGAMENTO_COM_BOLETO (DATA_PAGAMENTO, PEDIDO_ID) VALUES ('2017-10-20', 2)
