DECLARE @CATEGORIA_INFORMATICA INTEGER;
DECLARE @CATEGORIA_ESCRITORIO INTEGER;
DECLARE @PRODUTO_COMPUTADOR INTEGER;
DECLARE @PRODUTO_IMPRESSORA INTEGER;
DECLARE @PRODUTO_MOUSE INTEGER;

INSERT INTO CATEGORIA (NOME) values ('Informática');
INSERT INTO CATEGORIA (NOME) values ('Escritório');

SET @CATEGORIA_INFORMATICA = SELECT ID FROM CATEGORIA WHERE NOME = 'Informática'
SET @CATEGORIA_ESCRITORIO = SELECT ID FROM CATEGORIA WHERE NOME = 'Escritório'

INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Computador', 2000.0);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Impressora', 800.0);
INSERT INTO PRODUTO (NOME, PRECO) VALUES ('Mouse', 80.0);

SET @PRODUTO_COMPUTADOR = SELECT ID FROM PRODUTO WHERE NOME = 'Computador'
SET @PRODUTO_IMPRESSORA = SELECT ID FROM PRODUTO WHERE NOME = 'Impressora'
SET @PRODUTO_MOUSE = SELECT ID FROM PRODUTO WHERE NOME = 'Mouse'

INSERT INTO PRODUTO_CATEGORIA (CATEGORIA_ID, PRODUTO_ID) VALUES (@CATEGORIA_INFORMATICA, @PRODUTO_COMPUTADOR);
INSERT INTO PRODUTO_CATEGORIA (CATEGORIA_ID, PRODUTO_ID) VALUES (@CATEGORIA_ESCRITORIO, @PRODUTO_IMPRESSORA);
INSERT INTO PRODUTO_CATEGORIA (CATEGORIA_ID, PRODUTO_ID) VALUES (@CATEGORIA_ESCRITORIO, @PRODUTO_MOUSE);